config/routes.rb
HackerNews::Application.routes.draw do
  resources :stories, :except => :show do  
    resources :comments, :except => :show
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions, :except => :show, :except => :index
  resources :users, :except => :show, :except => :index

  root :to => 'stories#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :story_id, :presence => true
  attr_accessible :text, :story_id

 belongs_to :story

end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, :url, :presence => true
  attr_accessible :title, :url

  has_many :comments

  before_save :title_case

  private

  def title_case
    self.title = self.title.split(' ').map {|word| word.capitalize}.join(' ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :password_digest
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end  

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Story.find(params[:story_id]).comments.build
  end

  def create
    @comment = Comment.new(params[:comment])
    #@comment = Story.find(params[:story_id]).comments.create(params[:comment])

    if @comment.save
      flash[:notice] = "Your comment was successfully created."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # p params
    # @comment = Comment.find(params[:id])
    # @story = 
    @comment = Story.find(params[:story_id]).comments.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Your comment was successfully deleted."
    redirect_to story_comments_path
  end

  def index
    @comments = Comment.all
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "Your comment was successfully updated."
      redirect_to root_path
    else
      render :update
    end 
  end 

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      redirect_to new_session_path, notice: "Email or password is invalid."
      #flash.now.alert = "Email or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_filter :authorize, only: [:edit, :update, :new]

  def new
    @story = Story.new
  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @story = Story.new(params[:story])

    if @story.save
      flash[:notice] = "Your story was successfully created."
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    flash[:notice] = "Your story was successfully deleted."
    redirect_to stories_path
  end

  def index
    @stories = Story.all
    @comments = Comment.all
  end

  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      flash[:notice] = "Your story was successfully updated."
      redirect_to root_path
    else
      render :edit
    end 
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@comment.story, @comment] do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.label :story_id %>
  <%= f.text_field :story_id %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<% provide :title, "Edit Comment" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<% provide :title, "New comment" %>

<h2>Comments about this item...</h2>

<table>
<tr>
  <td>Story Title: </td>
</tr>
  <tr>
    <td>Posted</td>
    <td> </td>
    <td>Comment</td>
  </tr>
  <% @comments.sort_by(&:created_at).reverse.each do |comment| %>
    <tr>
      <td><%= comment.created_at.strftime("%m/%d/%Y- %H:%M - ") %></td>
      <td><%= comment.text %></td>
      <td> </td>
      <td><p><%= link_to 'Change', edit_story_comment_path(comment) %></p> </td>
      <td><%= link_to 'Delete', comment, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add comment', new_story_comment_path %></p>

app/views/comments/new.html.erb
<% provide :title, "New Comment" %>

<%= render 'form' %>

app/views/comments/update.html.erb
<% provide :title, "Update Comment" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacker News Clone | <%= yield :title %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", logout_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
    <% end %>
</div>
  </div>
  <h1>Hacker News Clone - <%= yield :title %></h1>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>

</body>


</html>

app/views/stories/new.html.erb
<% provide :title, "New Story" %>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>